### ISSUE TITLE
Release 0.0.14: IndexError: list index out of range

### ISSUE THREAD

**Issue by JayBraker** [soul-catcher/mypy-gitlab-code-quality#4]
Hi,

since the release of 0.0.14 I get this IndexError when attempting to run the module.
Call is made like "mypy src/ --no-error-summary | PYTHONHASHSEED=0 mypy-gitlab-code-quality"
Works fine with 0.0.13

```Traceback (most recent call last):
  File "/home/executor/.local/share/hatch/env/virtual/transferify/m--aXEsD/transferify/bin/mypy-gitlab-code-quality", line 8, in <module>
    sys.exit(main())
  File "/home/executor/.local/share/hatch/env/virtual/transferify/m--aXEsD/transferify/lib/python3.10/site-packages/mypy_gitlab_code_quality/__init__.py", line 83, in main
    parse_lines(stdin),
  File "/home/executor/.local/share/hatch/env/virtual/transferify/m--aXEsD/transferify/lib/python3.10/site-packages/mypy_gitlab_code_quality/__init__.py", line 74, in parse_lines
    append_line_to_issues(
  File "/home/executor/.local/share/hatch/env/virtual/transferify/m--aXEsD/transferify/lib/python3.10/site-packages/mypy_gitlab_code_quality/__init__.py", line 38, in append_line_to_issues
    if is_info_to_previous_issue(issues, severity, lineNumber):
  File "/home/executor/.local/share/hatch/env/virtual/transferify/m--aXEsD/transferify/lib/python3.10/site-packages/mypy_gitlab_code_quality/__init__.py", line 26, in is_info_to_previous_issue
    issues[-1]["location"]["lines"]["begin"] == lineNumber
IndexError: list index out of range
```

If I can provide any additional info for tracing the issue, let me know!
Really appreciate this handy conversion tool, great job :>

Kind regards

**Comment by OokamiTheLord** [comment]
Hi, @JayBraker 

Could you provide raw mypy output (instead of mypy-gitlab-code-quality pipe it to file)?
It's my PR that's at fault, probably missed some corner case

**Comment by soul-catcher** [comment]
Thank you for opening Issue!

Seems IndexError happens when the first line in mypy output has `note` level like this:

```
mypy_gitlab_code_quality/__init__.py:23: note: Missing type parameters for generic type "dict"
mypy_gitlab_code_quality/__init__.py:31: error: Missing type parameters for generic type "dict"
mypy_gitlab_code_quality/__init__.py:56: error: Missing type parameters for generic type "dict"
mypy_gitlab_code_quality/__init__.py:57: error: Missing type parameters for generic type "dict"
```

Check if there are another issues before chaining new one should fix this problem.
